### ISSUE TITLE
Samus built in speakers

### ISSUE THREAD

**Issue by kcalvinalvin** [benley/dotfiles#3]
https://github.com/benley/dotfiles/blob/51c317c994db8530e2c94bf854aefb55046f546f/machines/samus/configuration.nix#L32-L38

Just curious but did the audio ever work for you for Chromebook 2015 LS (aka Samus)? I haven't had any luck with mine and am wondering if there is any hope in me trying to get it to work.

**Comment by benley** [comment]
Audio was definitely working for me when I ran NixOS on this device!  Unfortunately I can't easily verify it now because my Samus device has gone back to being a normal chromebook, but it _should_ be possible to get it working.

**Comment by kcalvinalvin** [comment]
Hmmm I should give it another go then. Thanks!
